// 5 built-in GroupStyles. Each is a plain object — adding more is a
// one-liner. styleId is the FK from CaptionGroup.styleId.

import type { GroupStyle } from '@/lib/api';

export const DEFAULT_GROUP_STYLES: Record<string, GroupStyle> = {
  clean: {
    id: 'clean',
    name: 'Clean',
    bg: 'rgba(0,0,0,0.55)',
    text: '#ffffff',
    activeBg: 'rgba(0,0,0,0.8)',
    activeText: '#ffffff',
    weight: 700,
    scaleActive: 1.08,
    rotateActive: 0,
    baseFontSize: 64,
    padX: 0.35,
    padY: 0.2,
    radius: 0.25,
    glow: null,
    color: '#9ca3af',
  },
  pop: {
    id: 'pop',
    name: 'Pop',
    bg: 'rgba(255,255,255,0.92)',
    text: '#0f172a',
    activeBg: '#fde047',
    activeText: '#0f172a',
    weight: 800,
    scaleActive: 1.22,
    rotateActive: -4,
    baseFontSize: 72,
    padX: 0.45,
    padY: 0.25,
    radius: 0.35,
    glow: null,
    color: '#fde047',
  },
  emphasis: {
    id: 'emphasis',
    name: 'Emphasis',
    bg: 'rgba(0,0,0,0.65)',
    text: '#ffffff',
    activeBg: '#ef4444',
    activeText: '#ffffff',
    weight: 900,
    scaleActive: 1.3,
    rotateActive: 0,
    baseFontSize: 80,
    padX: 0.4,
    padY: 0.22,
    radius: 0.18,
    glow: 'rgba(239,68,68,0.55)',
    color: '#ef4444',
  },
  whisper: {
    id: 'whisper',
    name: 'Whisper',
    bg: 'transparent',
    text: 'rgba(255,255,255,0.78)',
    activeBg: 'transparent',
    activeText: '#ffffff',
    weight: 500,
    scaleActive: 1.04,
    rotateActive: 0,
    baseFontSize: 52,
    padX: 0.25,
    padY: 0.15,
    radius: 0.1,
    glow: null,
    color: '#a5b4fc',
  },
  action: {
    id: 'action',
    name: 'Action',
    bg: '#0f172a',
    text: '#fef3c7',
    activeBg: '#22d3ee',
    activeText: '#0f172a',
    weight: 800,
    scaleActive: 1.18,
    rotateActive: 3,
    baseFontSize: 70,
    padX: 0.4,
    padY: 0.24,
    radius: 0.3,
    glow: 'rgba(34,211,238,0.6)',
    color: '#22d3ee',
  },
};

export const DEFAULT_GROUP_STYLE_ID = 'clean';
